---
all:
  children:
    managed:
      hosts:
        rhel1:
          ansible_host: 192.0.2.101
        rhel2:
          ansible_host: 192.0.2.102
        rhel3:
          ansible_host: 192.0.2.103
