---
webserver_package: httpd
webserver_service: httpd

webserver_document_root: "/var/www/html/{{ ansible_user }}"
webserver_title: "Ansible Workshop - {{ ansible_user }}"

webserver_config_file: "/etc/httpd/conf.d/{{ ansible_user }}.conf"