---
- name: Work with lists
  hosts: managed
  gather_facts: false

  vars:
    packages:
      - httpd
      - curl
      - vim-enhanced
      - tar

  tasks:
    - name: Display entire package list
      ansible.builtin.debug:
        var: packages

    - name: Display first package
      ansible.builtin.debug:
        msg: "The first package is {{ packages[0] }}"

    - name: Display third package
      ansible.builtin.debug:
        msg: "The third package is {{ packages[2] }}"
