---
- name: Configure firewall
  hosts: managed
  become: true

  tasks:
    - name: Make sure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow HTTP traffic
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
