---
- name: Package loop
  hosts: managed
  become: true

  vars:
    training_packages:
      - curl
      - wget
      - tar
      - vim-enhanced

  tasks:
    - name: Install training packages one by one
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ training_packages }}"
